//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Agancy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class providing_travel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public providing_travel()
        {
            this.reservations = new HashSet<reservation>();
        }
    
        public int id { get; set; }
        public Nullable<int> travel_id { get; set; }
        public Nullable<int> company_id { get; set; }
    
        public virtual company company { get; set; }
        public virtual travel travel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservations { get; set; }
    }
}
