//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Agancy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id { get; set; }
        public string bus_tag { get; set; }
        public Nullable<int> TravelCompanyId { get; set; }
        public Nullable<int> passenger_id { get; set; }
    
        public virtual providing_travel providing_travel { get; set; }
        public virtual User User { get; set; }
    }
}
